version: "2"
linters:
  default: none
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - unused
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - broker_test.go
      - codec_test.go
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - unused
          - staticcheck
formatters:
  enable:
    - gofmt
    - goimports
